pkgname = "sqlite"
output = "models"
no-tests = true
wipe = true
no-hooks = true
add-enum-types = true
add-soft-deletes = true

[sqlite3]
dbname = "../../build/db/data.db"
blacklist = ["schema_migrations"]

[aliases.tables.qso.columns]
rst_rcvd = "RstRcvd"
rst_sent = "RstSent"
rx_pwr = "RxPwr"
tx_pwr = "TxPwr"
fwd_uid = "FwdUid"
sm_qso_upload_date = "SmQsoUploadDate"
sm_qso_upload_status = "SmQsoUploadStatus"
sm_fwrd_by_email_date = "SmFwrdByEmailDate"
sm_fwrd_by_email_status = "SmFwrdByEmailStatus"
qslmsg = "QslMsg"
qslmsg_rcvd = "QslMsgRcvd"
qsl_rcvd = "QslRcvd"
qsl_rcvd_via = "QslRcvdVia"
qsl_rcvd_notes = "QslRcvdNotes"
qsl_sent = "QslSent"
qsl_sent_via = "QslSentVia"
qsl_via = "QslVia"
qsl_wanted = "QslWanted"

[aliases.tables.country.columns]
itu_zone = "ITUZone"
cq_zone = "CQZone"

[aliases.tables.operator.columns]
itu_zone = "ITUZone"

[aliases.tables.logbook.columns]
tx_pwr = "TxPwr"
