services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smpgadmin
    env_file:
      - .env
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@localhost}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    depends_on:
      - postgresql
    volumes:
      - ../../build/pgadmin_data:/var/lib/pgadmin

  postgresql:
    image: postgres:15-alpine
    env_file:
      - .env
    restart: always
    container_name: smpostgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-smuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1q2w3e4r}
      POSTGRES_DB: ${POSTGRES_DB:-station_manager}
    volumes:
      - ../../build/db/postgres_data:/var/lib/postgresql/data

volumes:
  pgadmin_data:
    driver: local
