pkgname = "models"
output   = "models"
wipe     = true
no-tests = true
no-hooks = true
add-enum-types = true

[psql]
user = "smuser"
dbname = "station_manager"
host = "localhost"
sslmode = "disable"
blacklist = ["schema_migrations"]

[aliases.tables.qso.columns]
rst_rcvd = "RstRcvd"
rst_sent = "RstSent"
