pkgname = "models"
output   = "models"
wipe     = true
no-tests = true
no-hooks = true
add-enum-types = true
#add-soft-deletes = true

[psql]
user = "smuser"
dbname = "station_manager"
host = "localhost"
port = 5432
sslmode = "disable"
blacklist = ["schema_migrations"]

[aliases.tables.qso.columns]
rst_rcvd = "RstRcvd"
rst_sent = "RstSent"
